require('../utils/requires.js');

/* globals gulp */
/* globals runSequence */
/* globals isDevBuild */
/* globals fontYellowBold */
/* globals config */
/* globals modified */
/* globals autoprefixer */
/* globals sass */
/* globals rename */
/* globals tap */
/* globals path */

const AUTOPREFIXER_BROWSERS = config.autoprefixer;

const ELEMENTS_SASS = config.path.srcElements + '/**/*.scss';

const YEAR = new Date().getFullYear();

const COPYRIGHT = config.copyright;

const PREFIX = '<!-- DO NOT EDIT - this file is generated by a script -->\n' +
               '<dom-module id="{{style-id}}">\n<template>\n<style>\n';

const SUFFIX = '</style>\n</template>\n</dom-module>\n';

const bundleSass = (file) => {
  let content = file.contents.toString();
  let filename = file.path;
  const regexStyleId = new RegExp('{{style-id}}', 'gi');
  const regexYear = new RegExp('{{year}}', 'gi');

  filename = path.win32.basename(filename, '.html');

  content = COPYRIGHT + PREFIX + content + SUFFIX;
  content = content.replace(regexStyleId, filename);
  content = content.replace(regexYear, YEAR);

  return content;
}

// All sass tasks - development
gulp.task('sass:dev', (callback) => {

  return gulp.src(ELEMENTS_SASS)
             .pipe(modified('sass:dev'))
             .pipe(sass())
             .pipe(autoprefixer(AUTOPREFIXER_BROWSERS))
             .pipe(rename({
                suffix: '-styles',
                extname: '.html'
              }))
             .pipe(tap((file) => {
               file.contents = new Buffer(bundleSass(file));
             }))
             .pipe(gulp.dest(config.path.srcElements));
});
